In [14]:
import numpy as np
a = np.random.randint(1, 99, size = 16)
print("랜덤함수: ", list(a))
aa = np.reshape(list(a), (2,8))
print("이차원배열: \n",aa)
A = aa.copy()
print("벡터 : ", A.shape)
print("차원정보확인 : ", A.ndim)
print("서브벡터크기 : ", len(A[0]))
print("전체출력 : \n", A)

max_value = -1
for i in A:
    for j in i:
        if max_value < j:
            max_value = j
print("전체 최댓값(All): ",  max_value)
'''
for, shape를 이용한 최댓값 찾기
'''
sub_value0 = -1
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if sub_value0 < A[i][j]:
            sub_value0 = A[i][j]
print("SUBMAX 0: ",  sub_value0)

sub_value1 = -1
for i in A[1]:
        if sub_value1 < i:
            sub_value1 = i
print("SUBMAX 1: ",  sub_value1)

print("-------함수 사용 버전--------")
print("ALL : ", np.max(A))
print("SUBMAX 0 : ", np.max(A[0]))
print("SUBMAX 1 : ", np.max(A[1]))

랜덤함수:  [59, 35, 59, 89, 91, 78, 25, 73, 4, 6, 42, 88, 42, 52, 47, 15]
이차원배열: 
 [[59 35 59 89 91 78 25 73]
 [ 4  6 42 88 42 52 47 15]]
벡터 :  (2, 8)
차원정보확인 :  2
서브벡터크기 :  8
전체출력 : 
 [[59 35 59 89 91 78 25 73]
 [ 4  6 42 88 42 52 47 15]]
전체 최댓값(All):  91
SUBMAX 0:  91
SUBMAX 1:  88
-------함수 사용 버전--------
ALL :  91
SUBMAX 0 :  91
SUBMAX 1 :  88


In [15]:
B = np.reshape(A, (2,2,4))
print("삼차원배열: \n",B)
print("벡터 : ", B.shape)
print("차원정보확인 : ", B.ndim)
print("전체출력 : \n", B)

삼차원배열: 
 [[[59 35 59 89]
  [91 78 25 73]]

 [[ 4  6 42 88]
  [42 52 47 15]]]
벡터 :  (2, 2, 4)
차원정보확인 :  3
전체출력 : 
 [[[59 35 59 89]
  [91 78 25 73]]

 [[ 4  6 42 88]
  [42 52 47 15]]]


In [16]:
B_01 = B[0, : , 0:2]
B_02 = B[0, : , 2:4]
print("B_01: \n", B_01)
print("B_02: \n", B_02)

C = B.copy()
print("C: \n", C)
C[:, : , [0,1]] = B[:, : , [2,3]]
C[:, : , [2,3]] = B[:, : , [0,1]]

print("C: \n", C)

B_01: 
 [[59 35]
 [91 78]]
B_02: 
 [[59 89]
 [25 73]]
C: 
 [[[59 35 59 89]
  [91 78 25 73]]

 [[ 4  6 42 88]
  [42 52 47 15]]]
C: 
 [[[59 89 59 35]
  [25 73 91 78]]

 [[42 88  4  6]
  [47 15 42 52]]]
